[build]
  base = "."
  publish = "."
  command = "npm run build"

[dev]
  command = "npm run dev"

[functions]
  directory = "functions"

[build.environment]
  OPENAI_API_KEY = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
